use_frameworks!

platform :ios, '10.0'

target 'LYPLoad_Example' do
  pod 'LYPLoad', :path => '../'

  target 'LYPLoad_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
